[package]
name = "typort-lsp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.78"
tokio = { version = "1.17.0", features = ["full"] }
#tower-lsp = { version = "0.19.0", features = ["proposed"]}
lsp-types = "0.95"
lsp-server = "0.7.7"
ropey = "1.5.0"
serde = { version = "1.0", features = ["derive"] }

typort-parser = { path="../typort-parser" }
typort-tyck = { path="../typort-tyck" }
# typort-interpreter = { path="../typort-interpreter" }
