[package]
name = "typort-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macro_parser_combinator = { git = "https://github.com/yportne13/macro_parser_combinator.git", branch = "LazyError" }
